def shared_pods
    # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        # the following ones are the ones taken from "Libraries" in Xcode:
        'RCTAnimation',
        'RCTActionSheet',
        'RCTBlob',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    
    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    # Specific deps
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
    
    pod 'react-native-onesignal',
        :path => "../node_modules/react-native-onesignal/react-native-onesignal.podspec",
        :inhibit_warnings => true
    pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'
end


# The target name is most likely the name of your project.
target 'AskAGirl' do
    shared_pods
end

# https://github.com/facebook/react-native/issues/12615#issuecomment-321264639
target 'AskAGirlTests' do
    shared_pods
end

# The following is needed to ensure the "archive" step works in XCode.
# It removes React from the Pods project, as it is already included in the main project.
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if target.name == "React"
#      target.remove_from_project
#    end
#  end
#end
